//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCanTeen.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ORDER_DETAIL
    {

        [Required(ErrorMessage = "Order Detail code is required")]
        [Display(Name = "code")]
        public int ID { get; set; }

        [Required(ErrorMessage = "Order code is required")]
        [Display(Name = "Order code")]
        public int ORDER_ID { get; set; }

        [Required(ErrorMessage = "Menu code is required")]
        [Display(Name = "Menu code")]
        public int MENU_ID { get; set; }

        [Required(ErrorMessage = "Quantity is required")]
        [Display(Name = "Quantity")]
        [Range(1, Int32.MaxValue)]
        public int QUANTITY { get; set; }

        [Required(ErrorMessage = "Price is required")]
        [Display(Name = "Price")]
        [Range(1000, Int32.MaxValue)]
        public int PRICE { get; set; }
    
        public virtual MENU MENU { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
